import { FileText, Calendar, Pill, User, Printer } from 'lucide-react'

const PrescriptionCard = ({ prescription, showPrint = true }) => {
  const handlePrint = () => {
    const printContent = `
      <html>
      <head>
        <title>Prescription - ${prescription.patient_name}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
          .header { border-bottom: 3px solid #DC2626; padding-bottom: 20px; margin-bottom: 30px; }
          .header h1 { color: #DC2626; font-size: 28px; margin: 0; }
          .header p { margin: 5px 0; color: #666; }
          .section { margin-bottom: 24px; }
          .section h3 { color: #DC2626; border-bottom: 1px solid #eee; padding-bottom: 8px; margin-bottom: 12px; }
          .medicine { background: #f9f9f9; padding: 12px; border-radius: 8px; margin-bottom: 10px; border-left: 4px solid #DC2626; }
          .medicine h4 { margin: 0 0 6px 0; color: #333; }
          .medicine p { margin: 2px 0; color: #666; font-size: 14px; }
          .footer { margin-top: 40px; border-top: 1px solid #eee; padding-top: 20px; }
          .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
          .info-item label { font-weight: bold; color: #555; display: block; margin-bottom: 4px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>MediCare Prescription</h1>
          <p>Date: ${new Date(prescription.created_at).toLocaleDateString('en-PK', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
        </div>
        <div class="section info-grid">
          <div class="info-item"><label>Patient Name:</label>${prescription.patient_name}</div>
          <div class="info-item"><label>Doctor Name:</label>${prescription.doctor_name}</div>
        </div>
        <div class="section">
          <h3>Diagnosis</h3>
          <p>${prescription.diagnosis}</p>
        </div>
        <div class="section">
          <h3>Prescribed Medicines</h3>
          ${prescription.medicines?.map(med => `
            <div class="medicine">
              <h4>${med.name} - ${med.dosage}</h4>
              <p>Frequency: ${med.frequency}</p>
              <p>Duration: ${med.duration}</p>
            </div>
          `).join('')}
        </div>
        ${prescription.instructions ? `
          <div class="section">
            <h3>Special Instructions</h3>
            <p>${prescription.instructions}</p>
          </div>
        ` : ''}
        ${prescription.follow_up_date ? `
          <div class="section">
            <h3>Follow-up Date</h3>
            <p>${prescription.follow_up_date}</p>
          </div>
        ` : ''}
        <div class="footer">
          <p>This prescription was generated by MediCare Healthcare Platform</p>
        </div>
      </body>
      </html>
    `
    const printWindow = window.open('', '_blank')
    printWindow.document.write(printContent)
    printWindow.document.close()
    printWindow.print()
  }

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden hover:shadow-md transition-shadow">
      {/* Header */}
      <div className="bg-red-600 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center space-x-3">
          <FileText className="h-6 w-6 text-white" />
          <div>
            <h3 className="font-bold text-white">Prescription</h3>
            <p className="text-red-100 text-sm">
              {new Date(prescription.created_at).toLocaleDateString('en-PK', {
                year: 'numeric', month: 'long', day: 'numeric'
              })}
            </p>
          </div>
        </div>
        {showPrint && (
          <button onClick={handlePrint}
            className="flex items-center bg-white text-red-600 px-3 py-1.5 rounded-lg text-sm font-medium hover:bg-red-50 transition">
            <Printer className="h-4 w-4 mr-1" />Print
          </button>
        )}
      </div>

      <div className="p-6">
        {/* Patient & Doctor */}
        <div className="grid grid-cols-2 gap-4 mb-4">
          <div className="flex items-center space-x-2">
            <User className="h-4 w-4 text-red-500" />
            <div>
              <p className="text-xs text-gray-500">Patient</p>
              <p className="font-semibold text-sm">{prescription.patient_name}</p>
            </div>
          </div>
          <div className="flex items-center space-x-2">
            <User className="h-4 w-4 text-red-500" />
            <div>
              <p className="text-xs text-gray-500">Doctor</p>
              <p className="font-semibold text-sm">{prescription.doctor_name}</p>
            </div>
          </div>
        </div>

        {/* Diagnosis */}
        <div className="mb-4 p-3 bg-red-50 rounded-lg border border-red-100">
          <p className="text-xs font-semibold text-red-600 mb-1">DIAGNOSIS</p>
          <p className="text-gray-800 text-sm">{prescription.diagnosis}</p>
        </div>

        {/* Medicines */}
        <div className="mb-4">
          <p className="text-xs font-semibold text-gray-500 mb-2 flex items-center">
            <Pill className="h-3 w-3 mr-1" />PRESCRIBED MEDICINES
          </p>
          <div className="space-y-2">
            {prescription.medicines?.map((med, idx) => (
              <div key={idx} className="p-3 bg-gray-50 rounded-lg border border-gray-100">
                <div className="flex items-center justify-between mb-1">
                  <span className="font-semibold text-sm text-gray-800">{med.name}</span>
                  <span className="text-xs bg-red-100 text-red-600 px-2 py-0.5 rounded-full">{med.dosage}</span>
                </div>
                <div className="flex items-center space-x-4 text-xs text-gray-500">
                  <span>📅 {med.frequency}</span>
                  <span>⏱ {med.duration}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Instructions */}
        {prescription.instructions && (
          <div className="mb-4 p-3 bg-yellow-50 rounded-lg border border-yellow-100">
            <p className="text-xs font-semibold text-yellow-600 mb-1">SPECIAL INSTRUCTIONS</p>
            <p className="text-gray-700 text-sm">{prescription.instructions}</p>
          </div>
        )}

        {/* Follow up */}
        {prescription.follow_up_date && (
          <div className="flex items-center space-x-2 p-3 bg-green-50 rounded-lg border border-green-100">
            <Calendar className="h-4 w-4 text-green-600" />
            <div>
              <p className="text-xs font-semibold text-green-600">FOLLOW-UP DATE</p>
              <p className="text-gray-700 text-sm">{prescription.follow_up_date}</p>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

export default PrescriptionCard